baseURL = ""
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Pierrick Turelier - Smart Contract Engineer (Solidity, JavaScript, TypeScript)"
# Main Menu
[[menu.main]]
name = "Home"
url = "/#home"
weight = 1
[[menu.main]]
name = "About"
url = "/#about"
weight = 2
[[menu.main]]
name = "Work"
url = "/#portfolio"
weight = 3
[[menu.main]]
name = "Resume"
url = "/#resume"
weight = 4
[[menu.main]]
name = "Skills"
url = "/#skill"
weight = 5
[[menu.main]]
name = "Contact"
url = "/#contact"
weight = 6

# Sitemap Menu
[[menu.sitemap]]
name = "Home"
url = "#home"
weight = 1
[[menu.sitemap]]
name = "About me"
url = "#about"
weight = 2
[[menu.sitemap]]
name = "My Portfolio"
url = "#portfolio"
weight = 3
[[menu.sitemap]]
name = "My Experience"
url = "#resume"
weight = 4
[[menu.sitemap]]
name = "My Skills"
url = "#skill"
weight = 5
[[menu.sitemap]]
name = "Contact me"
url = "#contact"
weight = 6

[params]
blogPageURL = "blog"
copyright = "All right reserved copyright © Turelier LLC 2022"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "UA-25791988-1"
logo = "images/site-navigation/logo.png"

[params.address]
email = "pierrick@turelier.com"

# Social icons
[[params.social]]
icon = "fab fa-linkedin"
url = "https://www.linkedin.com/in/pierrickgt/"
weight = 1
[[params.social]]
icon = "fab fa-github"
url = "https://github.com/PierrickGT"
weight = 2
[[params.social]]
icon = "fab fa-codepen"
url = "https://codepen.io/PierrickGT"
weight = 3
[[params.social]]
icon = "fab fa-twitter"
url = "https://twitter.com/pierrickgt"
weight = 4
[[params.social]]
icon = "fab fa-instagram"
url = "https://www.instagram.com/pierrickgt/"
weight = 5
[[params.social]]
icon = "fab fa-goodreads"
url = "https://goodreads.com/pierrick"
weight = 6
[[params.social]]
icon = "fas fa-record-vinyl"
url = "https://www.discogs.com/user/PierrickGT/collection"
weight = 7
[[params.social]]
icon = "fas fa-gamepad"
url = "https://rawg.io/@pierrick"
weight = 8
[[params.social]]
icon = "fas fa-film"
url = "https://letterboxd.com/pierrick/"
weight = 9
[[params.social]]
icon = "fas fa-desktop"
url = "https://trakt.tv/users/pierrick"
weight = 10
